apiVersion: apps/v1
kind: Deployment

metadata:
  name: invint

spec:
  replicas: 1

  selector:
    matchLabels:
      app: invint

  template:
    metadata:
      labels:
        app: invint

    spec:
      containers:
      - name: invint

        image: invinteligence.azurecr.io/invint:latest

        imagePullPolicy: Always

        envFrom:
        - secretRef:
            name: invint-secrets

        volumeMounts:
        - name: data-volume
          mountPath: /app/data

        ports:
        - containerPort: 8000

      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: invint-data
